name: DeathSwap
version: 1.1
author: LielAmar
main: com.lielamar.deathswap.DeathSwap
description: A simple deathswap plugin

commands:
  deathswap:
    description: Start/Stop deathswap
    aliases: [ds]

permissions:
  deathswap.command:
    default: op
    description: access to the deathswap command